# Generated by Django 5.0.6 on 2024-07-07 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 7, 19, 30, 30, 892013, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
