# Generated by Django 5.0.6 on 2024-07-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_produccion_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='hora',
            new_name='fechahora',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='fecha',
        ),
    ]
