# Generated by Django 5.0.6 on 2024-07-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_produccion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='operador',
            field=models.CharField(max_length=100),
        ),
    ]
